package co.edu.upb.train_management_system.view;

import co.edu.upb.train_management_system.model.user.AbstractUserWithPower;

import javax.swing.*;
import java.awt.*;

public class AdminPanelView {
    private JFrame frame;

    public AdminPanelView(AbstractUserWithPower admin) {
        frame = new JFrame("Panel Administrador");
        frame.setSize(500, 350);
        frame.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        frame.setLocationRelativeTo(null);
        frame.setLayout(new BorderLayout(10, 10));

        // Header con nombre del admin
        JLabel header = new JLabel(
                "Bienvenido, " + admin.getFullName(),
                SwingConstants.CENTER
        );
        header.setFont(new Font("Arial", Font.BOLD, 16));
        header.setBorder(BorderFactory.createEmptyBorder(15, 0, 5, 0));

        // Panel de opciones (puedes agregar más botones aquí después)
        JPanel options = new JPanel(new GridLayout(2, 2, 10, 10));
        options.setBorder(BorderFactory.createEmptyBorder(20, 40, 20, 40));

        JButton btnVerUsuarios = new JButton("Ver Pasajeros");
        JButton btnCerrarSesion = new JButton("Cerrar Sesión");

        options.add(btnVerUsuarios);
        options.add(new JLabel()); // spacer
        options.add(new JLabel()); // spacer
        options.add(btnCerrarSesion);

        btnCerrarSesion.addActionListener(e -> {
            frame.dispose();
            new LoginView();
        });

        btnVerUsuarios.addActionListener(e -> {
            JOptionPane.showMessageDialog(frame, "Próximamente: lista de pasajeros.");
        });

        frame.add(header, BorderLayout.NORTH);
        frame.add(options, BorderLayout.CENTER);
        frame.setVisible(true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
    }
}