package co.edu.upb.train_management_system.view;

import co.edu.upb.train_management_system.model.user.AbstractUserWithPower;
import co.edu.upb.train_management_system.model.user.UserService;

import javax.swing.*;
import java.awt.*;

public class LoginView {
    private JFrame frame;
    private JTextField fieldId;
    private JPasswordField fieldPassword;
    private JLabel labelError;

    public LoginView() {
        frame = new JFrame("Admin Login");
        frame.setSize(350, 220);
        frame.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        frame.setResizable(false);
        frame.setLocationRelativeTo(null);
        frame.setLayout(new BorderLayout(10, 10));

        JPanel form = new JPanel(new GridLayout(3, 2, 8, 8));
        form.setBorder(BorderFactory.createEmptyBorder(20, 20, 10, 20));

        form.add(new JLabel("Identificación:"));
        fieldId = new JTextField();
        form.add(fieldId);

        form.add(new JLabel("Contraseña:"));
        fieldPassword = new JPasswordField();
        form.add(fieldPassword);

        JButton btnLogin = new JButton("Ingresar");
        form.add(new JLabel()); // spacer
        form.add(btnLogin);

        labelError = new JLabel("", SwingConstants.CENTER);
        labelError.setForeground(Color.RED);

        frame.add(form, BorderLayout.CENTER);
        frame.add(labelError, BorderLayout.SOUTH);

        btnLogin.addActionListener(e -> handleLogin());

        frame.setVisible(true);
    }

    private void handleLogin() {
        try {
            String id = fieldId.getText().trim();
            String password = new String(fieldPassword.getPassword());

            AbstractUserWithPower user = UserService.getInstance().login(id, password);

            if (user != null) {
                frame.dispose();
                new AdminPanelView(user); // abre el panel admin
            } else {
                labelError.setText("Credenciales incorrectas.");
            }
        } catch (NumberFormatException ex) {
            labelError.setText("La identificación debe ser un número.");
        } catch (Exception ex) {
            labelError.setText("Error: " + ex.getMessage());
        }
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
    }
}
