package co.edu.upb.train_management_system.view;

import java.util.function.UnaryOperator;

import co.edu.upb.train_management_system.model.history.History;
import co.edu.upb.train_management_system.model.observer.Observer;
import co.edu.upb.train_management_system.model.observer.Subject;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;

public class ServerView extends Observer {
    private JPanel mainPanel;
    private JButton button;
    private JPanel panelButton;
    private JPanel panelConsole;
    private JLabel console;
    private JButton stopButton;
    private JButton testButton;

    private String title;
    private JFrame frame;

    public ServerView(String title, Subject subject) {
        super(subject);
        this.title = title;
        // No inicializas los componentes aquí, el .form ya lo hace
    }

    public void initComponents(UnaryOperator<Void> onStart, UnaryOperator<Void> onStop) {
        console.setOpaque(true);
        console.setBackground(new Color(255, 255, 255));

        if (GraphicsEnvironment.isHeadless()) return;

        if (frame == null) frame = new JFrame(title);

        frame.setContentPane(mainPanel);
        frame.setSize(600, 250);
        frame.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        frame.setResizable(false);
        frame.setLocationRelativeTo(null);

        // Botón start
        button.addActionListener(event -> onStart.apply(null));

        // Botón stop — agrégalo en el .form con field name "stopButton"
        stopButton.setEnabled(false);
        stopButton.addActionListener(event -> onStop.apply(null));

        frame.setVisible(true);
    }

    public void startStatus(String status) {
        button.setText(status);
        button.setEnabled(false);
        stopButton.setEnabled(true); // ← habilita el stop
        this.getHistory().addAction(status);
    }

    public void stopStatus(String status) {
        button.setText(status);
        button.setEnabled(true);   // ← vuelve a habilitar start
        stopButton.setEnabled(false);
        this.getHistory().addAction(status);
    }

    public void showTestButton() {
        if (testButton == null) {
            testButton = new JButton("Prueba");
            testButton.addActionListener(e -> new LoginView());
            panelButton.add(testButton);
            panelButton.revalidate();
            panelButton.repaint();
        }
    }

    @Override
    public void update() {
        console.setText("Status: " + this.getHistory().getLastAction());
    }

    public History getHistory() {
        return (History) subject;
    }

    public void setMessage(String msg) {
        this.getHistory().addAction(msg);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(10, 10, 10, 10), -1, -1));
        mainPanel.setMinimumSize(new Dimension(600, 200));
        mainPanel.setPreferredSize(new Dimension(600, 200));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, 8));
        mainPanel.add(panel1, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        panelButton = new JPanel();
        panelButton.setLayout(new GridBagLayout());
        panel1.add(panelButton, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, 1, null, null, null, 0, false));
        button = new JButton();
        button.setText("Start Server");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 0.5;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panelButton.add(button, gbc);
        stopButton = new JButton();
        stopButton.setText("Stop Server");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.weightx = 0.5;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panelButton.add(stopButton, gbc);
        panelConsole = new JPanel();
        panelConsole.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(5, 10, 5, 10), -1, -1));
        panel1.add(panelConsole, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        panelConsole.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        console = new JLabel();
        console.setText("Status: Stopped.");
        console.setVerticalAlignment(1);
        panelConsole.add(console, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 5, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}
